name: Python Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.11-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: test_script
        run: python -m unittest test_utils.py

  build:
